#!/bin/bash

if [ $# -lt 1 ] ; then
  cat << EOM
  [usage]
    $0: $0 [KEYWORD-FOR-SERACH-PROJECTS]

    "gcloud projects list --filter" wrapper
EOM
  exit 0
fi

gcloud projects list --filter="$@"

exit 0
